module user_project_wrapper (user_clock2,
    wb_clk_i,
    wb_rst_i,
    wbs_ack_o,
    wbs_cyc_i,
    wbs_stb_i,
    wbs_we_i,
    vssa2,
    vdda2,
    vssa1,
    vdda1,
    vssd2,
    vccd2,
    vssd1,
    vccd1,
    analog_io,
    io_in,
    io_oeb,
    io_out,
    la_data_in,
    la_data_out,
    la_oenb,
    user_irq,
    wbs_adr_i,
    wbs_dat_i,
    wbs_dat_o,
    wbs_sel_i);
 input user_clock2;
 input wb_clk_i;
 input wb_rst_i;
 output wbs_ack_o;
 input wbs_cyc_i;
 input wbs_stb_i;
 input wbs_we_i;
 inout vssa2;
 inout vdda2;
 inout vssa1;
 inout vdda1;
 inout vssd2;
 inout vccd2;
 inout vssd1;
 inout vccd1;
 inout [28:0] analog_io;
 input [37:0] io_in;
 output [37:0] io_oeb;
 output [37:0] io_out;
 input [127:0] la_data_in;
 output [127:0] la_data_out;
 input [127:0] la_oenb;
 output [2:0] user_irq;
 input [31:0] wbs_adr_i;
 input [31:0] wbs_dat_i;
 output [31:0] wbs_dat_o;
 input [3:0] wbs_sel_i;

 wire afe_ibias;
 wire afe_nbias;
 wire afe_refby2;
 wire afe_refhi;
 wire afe_vout;
 wire afe_vref;

 CF_ADC_SAR12 u_cf_adc_sar12 (.en_pump_lv(la_data_in[20]),
    .vreflo(analog_io[22]),
    .scan_test_mode(la_data_in[21]),
    .test_scanin(la_data_in[22]),
    .test_scanen(la_data_in[23]),
    .hiz(la_data_in[13]),
    .sof(la_data_in[11]),
    .test_sea(la_data_in[24]),
    .reset_n(la_data_in[10]),
    .eof(la_data_out[12]),
    .iso_en(la_data_in[14]),
    .next(la_data_in[12]),
    .vinp(afe_vout),
    .vinm(analog_io[20]),
    .vrefhi(afe_refhi),
    .trimunit(la_data_in[16]),
    .vdda(analog_io[25]),
    .vgnd(vssd1),
    .VPUMP(analog_io[27]),
    .vssa(analog_io[26]),
    .refby2(afe_refby2),
    .pumpclk(la_data_in[19]),
    .pd(la_data_in[8]),
    .pd_ana(la_data_in[9]),
    .refclk(user_clock2),
    .vpwr(vccd1),
    .dly_inc(la_data_in[17]),
    .dcen(la_data_in[18]),
    .ibias2p5u(afe_ibias),
    .ibias2p5u_1(afe_ibias),
    .enable_hv(la_data_in[15]),
    .cap_trim({la_data_in[39],
    la_data_in[38],
    la_data_in[37]}),
    .data_out({la_data_out[11],
    la_data_out[10],
    la_data_out[9],
    la_data_out[8],
    la_data_out[7],
    la_data_out[6],
    la_data_out[5],
    la_data_out[4],
    la_data_out[3],
    la_data_out[2],
    la_data_out[1],
    la_data_out[0]}),
    .dft_inc({la_data_in[45],
    la_data_in[44],
    la_data_in[43],
    la_data_in[42]}),
    .dft_outc({la_data_in[48],
    la_data_in[47],
    la_data_in[46]}),
    .icont_lv({la_data_in[41],
    la_data_in[40]}),
    .resolution({la_data_in[26],
    la_data_in[25]}),
    .sample_width({la_data_in[36],
    la_data_in[35],
    la_data_in[34],
    la_data_in[33],
    la_data_in[32],
    la_data_in[31],
    la_data_in[30],
    la_data_in[29],
    la_data_in[28],
    la_data_in[27]}),
    .sel_csel_dft({la_data_in[52],
    la_data_in[51],
    la_data_in[50],
    la_data_in[49]}));
 CF_ADC_SAR12_sar_refs u_cf_adc_sar12_sar_refs (.vdda(analog_io[25]),
    .vpwr(vccd1),
    .VPUMP(analog_io[27]),
    .vssa(analog_io[26]),
    .vgnd(vssd1),
    .pd(la_data_in[8]),
    .hiz(la_data_in[13]),
    .REFBY2(afe_refby2),
    .pd_ana(la_data_in[9]),
    .EN_RESVDA(la_data_in[63]),
    .IREF_VCMBUF(afe_ibias),
    .sw_start(la_data_in[108]),
    .pd_vcmbuf(la_data_in[109]),
    .refout(analog_io[21]),
    .refout_en(la_data_in[118]),
    .sw_holdb(la_data_in[119]),
    .enpdb_hv(la_data_in[120]),
    .REFHI(afe_refhi),
    .enable_hv(la_data_in[15]),
    .IREF_VREFBUF(afe_ibias),
    .PD_BUF_VREF(la_data_in[121]),
    .vssa_shield(analog_io[26]),
    .dft_comp_en(la_data_in[122]),
    .PWR_CTRL_VREF({la_data_in[59],
    la_data_in[58]}),
    .S_LV({la_data_in[117],
    la_data_in[116],
    la_data_in[115],
    la_data_in[114],
    la_data_in[113],
    la_data_in[112],
    la_data_in[111],
    la_data_in[110]}),
    .muxsarref({la_data_in[62],
    la_data_in[61],
    la_data_in[60]}),
    .vref({la_data_in[57],
    la_data_in[56],
    la_data_in[55],
    la_data_in[54],
    la_data_in[53]}));
 CF_BGR u_cf_bgr (.finetune(la_data_in[96]),
    .en_startb(la_data_in[97]),
    .mux2sel(la_data_in[92]),
    .dft_sel(la_data_in[93]),
    .pd_ibg(la_data_in[95]),
    .pd(la_data_in[94]),
    .dft_curr_in(analog_io[24]),
    .vb2_fast(analog_io[0]),
    .Vout(afe_vref),
    .ibg_3uA(afe_nbias),
    .ibg_2p375uA(afe_ibias),
    .vgnd(vssd1),
    .vpwr(vccd1),
    .CurrAbsTrim({la_data_in[82],
    la_data_in[81],
    la_data_in[80],
    la_data_in[79],
    la_data_in[78],
    la_data_in[77]}),
    .inl_ctrl({la_data_in[89],
    la_data_in[88],
    la_data_in[87],
    la_data_in[86],
    la_data_in[85],
    la_data_in[84],
    la_data_in[83]}),
    .mux1sel({la_data_in[91],
    la_data_in[90]}),
    .trimCurr({la_data_in[76],
    la_data_in[75],
    la_data_in[74],
    la_data_in[73],
    la_data_in[72],
    la_data_in[71]}),
    .trimTC({la_data_in[70],
    la_data_in[69],
    la_data_in[68],
    la_data_in[67],
    la_data_in[66],
    la_data_in[65],
    la_data_in[64]}));
 CF_BUF_HIZ u_cf_buf_hiz (.tp(la_data_in[2]),
    .vgnd(vssd1),
    .clk2_boost(la_data_in[3]),
    .clk1_boostr(la_data_in[6]),
    .vbpt(analog_io[9]),
    .vbpcis(analog_io[16]),
    .vbncis(analog_io[17]),
    .vpwr(vccd1),
    .vout(afe_vout),
    .vbpci(analog_io[14]),
    .vbnt(analog_io[10]),
    .ibias(afe_ibias),
    .e_pd(la_data_in[0]),
    .vbnci(analog_io[15]),
    .vbpcid(analog_io[18]),
    .vbptd(analog_io[19]),
    .vbnc(analog_io[13]),
    .vbpc(analog_io[12]),
    .en_pd(la_data_in[1]),
    .vbpb(analog_io[11]),
    .vinp_n(analog_io[3]),
    .vinn_n(analog_io[4]),
    .vinp_na(analog_io[5]),
    .vinn_na(analog_io[6]),
    .vinn_p(analog_io[2]),
    .vinp_p(analog_io[1]),
    .e_na_boost(la_data_in[5]),
    .e_n_boost(la_data_in[4]));
 CF_REFBUF u_cf_refbuf (.nbias(afe_nbias),
    .out(analog_io[7]),
    .ref_1v2(afe_vref),
    .vgnd(vssd1),
    .pd(la_data_in[104]),
    .ng(analog_io[8]),
    .switchon(la_data_in[105]),
    .ch_cont(la_data_in[107]),
    .boost(la_data_in[106]),
    .vpwre(analog_io[8]),
    .ch2(analog_io[7]),
    .vpwr(vccd1),
    .ch1(analog_io[7]));
endmodule
